#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OBMPDataModel;

namespace OBMPDataModel	
{
	public partial class Billing
	{
		private long _iD;
		public virtual long ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private long? _salesOrderID;
		public virtual long? SalesOrderID
		{
			get
			{
				return this._salesOrderID;
			}
			set
			{
				this._salesOrderID = value;
			}
		}
		
		private long? _salesOrderDetailID;
		public virtual long? SalesOrderDetailID
		{
			get
			{
				return this._salesOrderDetailID;
			}
			set
			{
				this._salesOrderDetailID = value;
			}
		}
		
		private long? _customerID;
		public virtual long? CustomerID
		{
			get
			{
				return this._customerID;
			}
			set
			{
				this._customerID = value;
			}
		}
		
		private DateTime? _paymentDate;
		public virtual DateTime? PaymentDate
		{
			get
			{
				return this._paymentDate;
			}
			set
			{
				this._paymentDate = value;
			}
		}
		
		private long? _billedAmount;
		public virtual long? BilledAmount
		{
			get
			{
				return this._billedAmount;
			}
			set
			{
				this._billedAmount = value;
			}
		}
		
		private string _billMethod;
		public virtual string BillMethod
		{
			get
			{
				return this._billMethod;
			}
			set
			{
				this._billMethod = value;
			}
		}
		
		private string _billingAccountNumber;
		public virtual string BillingAccountNumber
		{
			get
			{
				return this._billingAccountNumber;
			}
			set
			{
				this._billingAccountNumber = value;
			}
		}
		
		private string _billingAccountName;
		public virtual string BillingAccountName
		{
			get
			{
				return this._billingAccountName;
			}
			set
			{
				this._billingAccountName = value;
			}
		}
		
		private string _invoiceReferenceNumber;
		public virtual string InvoiceReferenceNumber
		{
			get
			{
				return this._invoiceReferenceNumber;
			}
			set
			{
				this._invoiceReferenceNumber = value;
			}
		}
		
		private Customer _customer;
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
		}
		
		private Order _order;
		public virtual Order Order
		{
			get
			{
				return this._order;
			}
			set
			{
				this._order = value;
			}
		}
		
	}
}
#pragma warning restore 1591
