#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OBMPDataModel;

namespace OBMPDataModel	
{
	public partial class Customer
	{
		private long _iD;
		public virtual long ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _uID;
		public virtual string UID
		{
			get
			{
				return this._uID;
			}
			set
			{
				this._uID = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _accountReference;
		public virtual string AccountReference
		{
			get
			{
				return this._accountReference;
			}
			set
			{
				this._accountReference = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _contactPerson;
		public virtual string ContactPerson
		{
			get
			{
				return this._contactPerson;
			}
			set
			{
				this._contactPerson = value;
			}
		}
		
		private string _contactDetail;
		public virtual string ContactDetail
		{
			get
			{
				return this._contactDetail;
			}
			set
			{
				this._contactDetail = value;
			}
		}
		
		private IList<Order> _orders = new List<Order>();
		public virtual IList<Order> Orders
		{
			get
			{
				return this._orders;
			}
		}
		
		private IList<Billing> _billings = new List<Billing>();
		public virtual IList<Billing> Billings
		{
			get
			{
				return this._billings;
			}
		}
		
	}
}
#pragma warning restore 1591
