#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OBMPDataModel;
using Telerik.OpenAccess.Metadata.Relational;

namespace OBMPDataModel
{

	public partial class FluentModelMetadataSource : FluentMetadataSource
	{
		
		protected override IList<MappingConfiguration> PrepareMapping()
		{
			List<MappingConfiguration> mappingConfigurations = new List<MappingConfiguration>();
			
			MappingConfiguration<UserProfile> userprofileConfiguration = this.GetUserProfileMappingConfiguration();
			mappingConfigurations.Add(userprofileConfiguration);
			
			MappingConfiguration<SalesRepresentative> salesrepresentativeConfiguration = this.GetSalesRepresentativeMappingConfiguration();
			mappingConfigurations.Add(salesrepresentativeConfiguration);
			
			MappingConfiguration<SaleRepCustomer> salerepcustomerConfiguration = this.GetSaleRepCustomerMappingConfiguration();
			mappingConfigurations.Add(salerepcustomerConfiguration);
			
			MappingConfiguration<Product> productConfiguration = this.GetProductMappingConfiguration();
			mappingConfigurations.Add(productConfiguration);
			
			MappingConfiguration<Payment> paymentConfiguration = this.GetPaymentMappingConfiguration();
			mappingConfigurations.Add(paymentConfiguration);
			
			MappingConfiguration<Partner> partnerConfiguration = this.GetPartnerMappingConfiguration();
			mappingConfigurations.Add(partnerConfiguration);
			
			MappingConfiguration<OrderDetail> orderdetailConfiguration = this.GetOrderDetailMappingConfiguration();
			mappingConfigurations.Add(orderdetailConfiguration);
			
			MappingConfiguration<Order> orderConfiguration = this.GetOrderMappingConfiguration();
			mappingConfigurations.Add(orderConfiguration);
			
			MappingConfiguration<Customer> customerConfiguration = this.GetCustomerMappingConfiguration();
			mappingConfigurations.Add(customerConfiguration);
			
			MappingConfiguration<Billing> billingConfiguration = this.GetBillingMappingConfiguration();
			mappingConfigurations.Add(billingConfiguration);
			
			return mappingConfigurations;
		}
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "FluentModel";
			container.DefaultNamespace = "OBMPDataModel";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
		public MappingConfiguration<UserProfile> GetUserProfileMappingConfiguration()
		{
			MappingConfiguration<UserProfile> configuration = this.GetUserProfileClassConfiguration();
			this.PrepareUserProfilePropertyConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<UserProfile> GetUserProfileClassConfiguration()
		{
			MappingConfiguration<UserProfile> configuration = new MappingConfiguration<UserProfile>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("UserProfile");
	
			return configuration;
		}
	
		public void PrepareUserProfilePropertyConfigurations(MappingConfiguration<UserProfile> configuration)
		{
			configuration.HasProperty(x => x.UserId).IsIdentity(KeyGenerator.Autoinc).HasFieldName("_userId").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("UserId").IsNotNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.UserName).HasFieldName("_userName").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("UserName").IsNullable().HasColumnType("nvarchar(max)").HasLength(0);
		}
		public MappingConfiguration<SalesRepresentative> GetSalesRepresentativeMappingConfiguration()
		{
			MappingConfiguration<SalesRepresentative> configuration = this.GetSalesRepresentativeClassConfiguration();
			this.PrepareSalesRepresentativePropertyConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<SalesRepresentative> GetSalesRepresentativeClassConfiguration()
		{
			MappingConfiguration<SalesRepresentative> configuration = new MappingConfiguration<SalesRepresentative>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("SalesRepresentative");
	
			return configuration;
		}
	
		public void PrepareSalesRepresentativePropertyConfigurations(MappingConfiguration<SalesRepresentative> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity(KeyGenerator.Autoinc).HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.Name).HasFieldName("_name").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Name").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.Email).HasFieldName("_email").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Email").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.DateCreated).HasFieldName("_dateCreated").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("DateCreated").IsNullable().HasColumnType("date");
		}
		public MappingConfiguration<SaleRepCustomer> GetSaleRepCustomerMappingConfiguration()
		{
			MappingConfiguration<SaleRepCustomer> configuration = this.GetSaleRepCustomerClassConfiguration();
			this.PrepareSaleRepCustomerPropertyConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<SaleRepCustomer> GetSaleRepCustomerClassConfiguration()
		{
			MappingConfiguration<SaleRepCustomer> configuration = new MappingConfiguration<SaleRepCustomer>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("SaleRepCustomer");
	
			return configuration;
		}
	
		public void PrepareSaleRepCustomerPropertyConfigurations(MappingConfiguration<SaleRepCustomer> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity(KeyGenerator.Autoinc).HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.SalesRepresentativeID).HasFieldName("_salesRepresentativeID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SalesRepresentativeID").IsNotNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.CustomerID).HasFieldName("_customerID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerID").IsNotNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.MappedDate).HasFieldName("_mappedDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("MappedDate").IsNullable().HasColumnType("date");
		}
		public MappingConfiguration<Product> GetProductMappingConfiguration()
		{
			MappingConfiguration<Product> configuration = this.GetProductClassConfiguration();
			this.PrepareProductPropertyConfigurations(configuration);
			this.PrepareProductAssociationConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<Product> GetProductClassConfiguration()
		{
			MappingConfiguration<Product> configuration = new MappingConfiguration<Product>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("Product");
	
			return configuration;
		}
	
		public void PrepareProductPropertyConfigurations(MappingConfiguration<Product> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity(KeyGenerator.Autoinc).HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.Name).HasFieldName("_name").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Name").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.PartnerProductName).HasFieldName("_partnerProductName").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerProductName").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.SSOTProductName).HasFieldName("_sSOTProductName").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SSOTProductName").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.SAPProductName).HasFieldName("_sAPProductName").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SAPProductName").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.GSMISProductName).HasFieldName("_gSMISProductName").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("GSMISProductName").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.PartnerShareType).HasFieldName("_partnerShareType").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerShareType").IsNullable().HasColumnType("tinyint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.ShareValue1).HasFieldName("_shareValue1").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue1").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue2).HasFieldName("_shareValue2").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue2").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue3).HasFieldName("_shareValue3").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue3").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue4).HasFieldName("_shareValue4").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue4").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue5).HasFieldName("_shareValue5").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue5").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue6).HasFieldName("_shareValue6").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue6").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue7).HasFieldName("_shareValue7").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue7").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue8).HasFieldName("_shareValue8").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue8").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue9).HasFieldName("_shareValue9").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue9").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ShareValue10).HasFieldName("_shareValue10").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ShareValue10").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.Description).HasFieldName("_description").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Description").IsNullable().HasColumnType("nvarchar").HasLength(250);
			configuration.HasProperty(x => x.PartnerID).HasFieldName("_partnerID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerID").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.ActiveFlag).HasFieldName("_activeFlag").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ActiveFlag").IsNullable().HasColumnType("bit").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.DateRegistered).HasFieldName("_dateRegistered").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("DateRegistered").IsNullable().HasColumnType("datetime");
		}
	
		public void PrepareProductAssociationConfigurations(MappingConfiguration<Product> configuration)
		{
			configuration.HasAssociation(x => x.Partner).HasFieldName("_partner").WithOpposite(x => x.Products).ToColumn("PartnerID").HasConstraint((x, y) =>  x.PartnerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.OrderDetails).HasFieldName("_orderDetails").WithOpposite(x => x.Product).ToColumn("ProductID").HasConstraint((y, x) =>  x.ProductID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
		}
		
		public MappingConfiguration<Payment> GetPaymentMappingConfiguration()
		{
			MappingConfiguration<Payment> configuration = this.GetPaymentClassConfiguration();
			this.PreparePaymentPropertyConfigurations(configuration);
			this.PreparePaymentAssociationConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<Payment> GetPaymentClassConfiguration()
		{
			MappingConfiguration<Payment> configuration = new MappingConfiguration<Payment>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("Payment");
	
			return configuration;
		}
	
		public void PreparePaymentPropertyConfigurations(MappingConfiguration<Payment> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity().HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.SalesOrderID).HasFieldName("_salesOrderID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SalesOrderID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PartnerID).HasFieldName("_partnerID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerID").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PaymentDate).HasFieldName("_paymentDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PaymentDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.PaidAmount).HasFieldName("_paidAmount").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PaidAmount").IsNullable().HasColumnType("numeric").HasPrecision(18).HasScale(0);
			configuration.HasProperty(x => x.PaymentMethod).HasFieldName("_paymentMethod").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PaymentMethod").IsNullable().HasColumnType("nvarchar").HasLength(50);
		}
	
		public void PreparePaymentAssociationConfigurations(MappingConfiguration<Payment> configuration)
		{
			configuration.HasAssociation(x => x.Order).HasFieldName("_order").WithOpposite(x => x.Payments).ToColumn("SalesOrderID").HasConstraint((x, y) =>  x.SalesOrderID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Partner).HasFieldName("_partner").WithOpposite(x => x.Payments).ToColumn("PartnerID").HasConstraint((x, y) =>  x.PartnerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
		}
		
		public MappingConfiguration<Partner> GetPartnerMappingConfiguration()
		{
			MappingConfiguration<Partner> configuration = this.GetPartnerClassConfiguration();
			this.PreparePartnerPropertyConfigurations(configuration);
			this.PreparePartnerAssociationConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<Partner> GetPartnerClassConfiguration()
		{
			MappingConfiguration<Partner> configuration = new MappingConfiguration<Partner>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("Partner");
	
			return configuration;
		}
	
		public void PreparePartnerPropertyConfigurations(MappingConfiguration<Partner> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity(KeyGenerator.Autoinc).HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.Name).HasFieldName("_name").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Name").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.MSAReference).HasFieldName("_mSAReference").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("MSAReference").IsNullable().HasColumnType("nvarchar").HasLength(20);
			configuration.HasProperty(x => x.Address).HasFieldName("_address").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Address").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.PartnerType).HasFieldName("_partnerType").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerType").IsNullable().HasColumnType("nvarchar").HasLength(20);
			configuration.HasProperty(x => x.PartnerShare).HasFieldName("_partnerShare").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerShare").IsNullable().HasColumnType("tinyint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.DateRegistered).HasFieldName("_dateRegistered").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("DateRegistered").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.PrimaryContact).HasFieldName("_primaryContact").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PrimaryContact").IsNullable().HasColumnType("nvarchar").HasLength(25);
			configuration.HasProperty(x => x.PrimaryContactDetail).HasFieldName("_primaryContactDetail").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PrimaryContactDetail").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.SecondaryContact).HasFieldName("_secondaryContact").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SecondaryContact").IsNullable().HasColumnType("nvarchar").HasLength(25);
			configuration.HasProperty(x => x.SecondaryContactDetail).HasFieldName("_secondaryContactDetail").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SecondaryContactDetail").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.TechnicalContact).HasFieldName("_technicalContact").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("TechnicalContact").IsNullable().HasColumnType("nvarchar").HasLength(25);
			configuration.HasProperty(x => x.TechnicalContactDetail).HasFieldName("_technicalContactDetail").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("TechnicalContactDetail").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.AdminContact).HasFieldName("_adminContact").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("AdminContact").IsNullable().HasColumnType("nvarchar").HasLength(25);
			configuration.HasProperty(x => x.AdminContactDetail).HasFieldName("_adminContactDetail").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("AdminContactDetail").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.Escalation).HasFieldName("_escalation").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Escalation").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.MSAContractDocument).HasFieldName("_mSAContractDocument").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("MSAContractDocument").IsNullable().HasColumnType("binary");
			configuration.HasProperty(x => x.ServiceDescription).HasFieldName("_serviceDescription").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ServiceDescription").IsNullable().HasColumnType("nvarchar").HasLength(250);
		}
	
		public void PreparePartnerAssociationConfigurations(MappingConfiguration<Partner> configuration)
		{
			configuration.HasAssociation(x => x.Products).HasFieldName("_products").WithOpposite(x => x.Partner).ToColumn("PartnerID").HasConstraint((y, x) =>  x.PartnerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Payments).HasFieldName("_payments").WithOpposite(x => x.Partner).ToColumn("PartnerID").HasConstraint((y, x) =>  x.PartnerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.OrderDetails).HasFieldName("_orderDetails").WithOpposite(x => x.Partner).ToColumn("PartnerID").HasConstraint((y, x) =>  x.PartnerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
		}
		
		public MappingConfiguration<OrderDetail> GetOrderDetailMappingConfiguration()
		{
			MappingConfiguration<OrderDetail> configuration = this.GetOrderDetailClassConfiguration();
			this.PrepareOrderDetailPropertyConfigurations(configuration);
			this.PrepareOrderDetailAssociationConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<OrderDetail> GetOrderDetailClassConfiguration()
		{
			MappingConfiguration<OrderDetail> configuration = new MappingConfiguration<OrderDetail>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("OrderDetail");
	
			return configuration;
		}
	
		public void PrepareOrderDetailPropertyConfigurations(MappingConfiguration<OrderDetail> configuration)
		{
			configuration.HasProperty(x => x.SalesOrderID).HasFieldName("_salesOrderID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SalesOrderID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.SalesOrderDetailID).IsIdentity().HasFieldName("_salesOrderDetailID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SalesOrderDetailID").IsNotNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.CustomerID).HasFieldName("_customerID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PartnerID).HasFieldName("_partnerID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerID").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.ProductID).HasFieldName("_productID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ProductID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.UnitPrice).HasFieldName("_unitPrice").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("UnitPrice").IsNullable().HasColumnType("numeric").HasPrecision(18).HasScale(0);
			configuration.HasProperty(x => x.UnitPriceDiscount).HasFieldName("_unitPriceDiscount").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("UnitPriceDiscount").IsNullable().HasColumnType("numeric").HasPrecision(18).HasScale(0);
			configuration.HasProperty(x => x.OrderQuantity).HasFieldName("_orderQuantity").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OrderQuantity").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.LineTotal).HasFieldName("_lineTotal").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("LineTotal").IsNullable().HasColumnType("numeric").HasPrecision(18).HasScale(0);
			configuration.HasProperty(x => x.OptusStatus).HasFieldName("_optusStatus").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OptusStatus").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.OptusUpdatedBy).HasFieldName("_optusUpdatedBy").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OptusUpdatedBy").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.OptusUpdateDate).HasFieldName("_optusUpdateDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OptusUpdateDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.PartnerStatus).HasFieldName("_partnerStatus").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerStatus").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PartnerUpdatedBy).HasFieldName("_partnerUpdatedBy").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerUpdatedBy").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PartnerUpdateDate).HasFieldName("_partnerUpdateDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerUpdateDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.CustomerStatus).HasFieldName("_customerStatus").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerStatus").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.CustomerUpdatedBy).HasFieldName("_customerUpdatedBy").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerUpdatedBy").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.CustomerUpdateDate).HasFieldName("_customerUpdateDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerUpdateDate").IsNullable().HasColumnType("datetime");
		}
	
		public void PrepareOrderDetailAssociationConfigurations(MappingConfiguration<OrderDetail> configuration)
		{
			configuration.HasAssociation(x => x.Order).HasFieldName("_order").WithOpposite(x => x.OrderDetails).ToColumn("SalesOrderID").HasConstraint((x, y) =>  x.SalesOrderID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Partner).HasFieldName("_partner").WithOpposite(x => x.OrderDetails).ToColumn("PartnerID").HasConstraint((x, y) =>  x.PartnerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Product).HasFieldName("_product").WithOpposite(x => x.OrderDetails).ToColumn("ProductID").HasConstraint((x, y) =>  x.ProductID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
		}
		
		public MappingConfiguration<Order> GetOrderMappingConfiguration()
		{
			MappingConfiguration<Order> configuration = this.GetOrderClassConfiguration();
			this.PrepareOrderPropertyConfigurations(configuration);
			this.PrepareOrderAssociationConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<Order> GetOrderClassConfiguration()
		{
			MappingConfiguration<Order> configuration = new MappingConfiguration<Order>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("Order");
	
			return configuration;
		}
	
		public void PrepareOrderPropertyConfigurations(MappingConfiguration<Order> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity().HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.OrderDate).HasFieldName("_orderDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OrderDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.DueDate).HasFieldName("_dueDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("DueDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.Status).HasFieldName("_status").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Status").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.TotalSaleAmount).HasFieldName("_totalSaleAmount").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("TotalSaleAmount").IsNullable().HasColumnType("numeric").HasPrecision(18).HasScale(0);
			configuration.HasProperty(x => x.CustomerID).HasFieldName("_customerID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.SalesPersonID).HasFieldName("_salesPersonID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SalesPersonID").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.ModificationDate).HasFieldName("_modificationDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ModificationDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.OptusStatus).HasFieldName("_optusStatus").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OptusStatus").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.OptusUpdatedBy).HasFieldName("_optusUpdatedBy").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OptusUpdatedBy").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.OptusUpdateDate).HasFieldName("_optusUpdateDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("OptusUpdateDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.PartnerStatus).HasFieldName("_partnerStatus").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerStatus").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PartnerUpdatedBy).HasFieldName("_partnerUpdatedBy").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerUpdatedBy").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PartnerUpdateDate).HasFieldName("_partnerUpdateDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PartnerUpdateDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.CustomerStatus).HasFieldName("_customerStatus").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerStatus").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.CustomerUpdatedBy).HasFieldName("_customerUpdatedBy").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerUpdatedBy").IsNullable().HasColumnType("int").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.CustomerUpdateDate).HasFieldName("_customerUpdateDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerUpdateDate").IsNullable().HasColumnType("datetime");
		}
	
		public void PrepareOrderAssociationConfigurations(MappingConfiguration<Order> configuration)
		{
			configuration.HasAssociation(x => x.Payments).HasFieldName("_payments").WithOpposite(x => x.Order).ToColumn("SalesOrderID").HasConstraint((y, x) =>  x.SalesOrderID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.OrderDetails).HasFieldName("_orderDetails").WithOpposite(x => x.Order).ToColumn("SalesOrderID").HasConstraint((y, x) =>  x.SalesOrderID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Customer).HasFieldName("_customer").WithOpposite(x => x.Orders).ToColumn("CustomerID").HasConstraint((x, y) =>  x.CustomerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Billings).HasFieldName("_billings").WithOpposite(x => x.Order).ToColumn("SalesOrderID").HasConstraint((y, x) =>  x.SalesOrderID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
		}
		
		public MappingConfiguration<Customer> GetCustomerMappingConfiguration()
		{
			MappingConfiguration<Customer> configuration = this.GetCustomerClassConfiguration();
			this.PrepareCustomerPropertyConfigurations(configuration);
			this.PrepareCustomerAssociationConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<Customer> GetCustomerClassConfiguration()
		{
			MappingConfiguration<Customer> configuration = new MappingConfiguration<Customer>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("Customer");
	
			return configuration;
		}
	
		public void PrepareCustomerPropertyConfigurations(MappingConfiguration<Customer> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity(KeyGenerator.Autoinc).HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.UID).HasFieldName("_uID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("UID").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.Name).HasFieldName("_name").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Name").IsNullable().HasColumnType("nvarchar").HasLength(100);
			configuration.HasProperty(x => x.AccountReference).HasFieldName("_accountReference").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("AccountReference").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.Address).HasFieldName("_address").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("Address").IsNullable().HasColumnType("nvarchar").HasLength(200);
			configuration.HasProperty(x => x.ContactPerson).HasFieldName("_contactPerson").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ContactPerson").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.ContactDetail).HasFieldName("_contactDetail").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ContactDetail").IsNullable().HasColumnType("nvarchar").HasLength(200);
		}
	
		public void PrepareCustomerAssociationConfigurations(MappingConfiguration<Customer> configuration)
		{
			configuration.HasAssociation(x => x.Orders).HasFieldName("_orders").WithOpposite(x => x.Customer).ToColumn("CustomerID").HasConstraint((y, x) =>  x.CustomerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Billings).HasFieldName("_billings").WithOpposite(x => x.Customer).ToColumn("CustomerID").HasConstraint((y, x) =>  x.CustomerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
		}
		
		public MappingConfiguration<Billing> GetBillingMappingConfiguration()
		{
			MappingConfiguration<Billing> configuration = this.GetBillingClassConfiguration();
			this.PrepareBillingPropertyConfigurations(configuration);
			this.PrepareBillingAssociationConfigurations(configuration);

			return configuration;
		}

		public MappingConfiguration<Billing> GetBillingClassConfiguration()
		{
			MappingConfiguration<Billing> configuration = new MappingConfiguration<Billing>();
			configuration.MapType(x => new { }).WithConcurencyControl(OptimisticConcurrencyControlStrategy.Changed).ToTable("Billing");
	
			return configuration;
		}
	
		public void PrepareBillingPropertyConfigurations(MappingConfiguration<Billing> configuration)
		{
			configuration.HasProperty(x => x.ID).IsIdentity().HasFieldName("_iD").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("ID").IsNotNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.SalesOrderID).HasFieldName("_salesOrderID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SalesOrderID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.SalesOrderDetailID).HasFieldName("_salesOrderDetailID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("SalesOrderDetailID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.CustomerID).HasFieldName("_customerID").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("CustomerID").IsNullable().HasColumnType("bigint").HasPrecision(0).HasScale(0);
			configuration.HasProperty(x => x.PaymentDate).HasFieldName("_paymentDate").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("PaymentDate").IsNullable().HasColumnType("datetime");
			configuration.HasProperty(x => x.BilledAmount).HasFieldName("_billedAmount").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("BilledAmount").IsNullable().HasColumnType("numeric").HasPrecision(18).HasScale(0);
			configuration.HasProperty(x => x.BillMethod).HasFieldName("_billMethod").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("BillMethod").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.BillingAccountNumber).HasFieldName("_billingAccountNumber").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("BillingAccountNumber").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.BillingAccountName).HasFieldName("_billingAccountName").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("BillingAccountName").IsNullable().HasColumnType("nvarchar").HasLength(50);
			configuration.HasProperty(x => x.InvoiceReferenceNumber).HasFieldName("_invoiceReferenceNumber").WithDataAccessKind(DataAccessKind.ReadWrite).ToColumn("InvoiceReferenceNumber").IsNullable().HasColumnType("nvarchar").HasLength(50);
		}
	
		public void PrepareBillingAssociationConfigurations(MappingConfiguration<Billing> configuration)
		{
			configuration.HasAssociation(x => x.Customer).HasFieldName("_customer").WithOpposite(x => x.Billings).ToColumn("CustomerID").HasConstraint((x, y) =>  x.CustomerID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
			configuration.HasAssociation(x => x.Order).HasFieldName("_order").WithOpposite(x => x.Billings).ToColumn("SalesOrderID").HasConstraint((x, y) =>  x.SalesOrderID == y.ID ).WithDataAccessKind(DataAccessKind.ReadWrite);
		}
		
	}
}
#pragma warning restore 1591
