#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OBMPDataModel;

namespace OBMPDataModel	
{
	public partial class FluentModel : OpenAccessContext, IFluentModelUnitOfWork
	{
		private static string connectionStringName = @"OBMPConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = new FluentModelMetadataSource();
		
		public FluentModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public FluentModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public FluentModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public FluentModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public FluentModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<UserProfile> UserProfiles 
		{
			get
			{
				return this.GetAll<UserProfile>();
			}
		}
		
		public IQueryable<SalesRepresentative> SalesRepresentatives 
		{
			get
			{
				return this.GetAll<SalesRepresentative>();
			}
		}
		
		public IQueryable<SaleRepCustomer> SaleRepCustomers 
		{
			get
			{
				return this.GetAll<SaleRepCustomer>();
			}
		}
		
		public IQueryable<Product> Products 
		{
			get
			{
				return this.GetAll<Product>();
			}
		}
		
		public IQueryable<Payment> Payments 
		{
			get
			{
				return this.GetAll<Payment>();
			}
		}
		
		public IQueryable<Partner> Partners 
		{
			get
			{
				return this.GetAll<Partner>();
			}
		}
		
		public IQueryable<OrderDetail> OrderDetails 
		{
			get
			{
				return this.GetAll<OrderDetail>();
			}
		}
		
		public IQueryable<Order> Orders 
		{
			get
			{
				return this.GetAll<Order>();
			}
		}
		
		public IQueryable<Customer> Customers 
		{
			get
			{
				return this.GetAll<Customer>();
			}
		}
		
		public IQueryable<Billing> Billings 
		{
			get
			{
				return this.GetAll<Billing>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}
	
	public interface IFluentModelUnitOfWork : IUnitOfWork
	{
		IQueryable<UserProfile> UserProfiles
		{
			get;
		}
		IQueryable<SalesRepresentative> SalesRepresentatives
		{
			get;
		}
		IQueryable<SaleRepCustomer> SaleRepCustomers
		{
			get;
		}
		IQueryable<Product> Products
		{
			get;
		}
		IQueryable<Payment> Payments
		{
			get;
		}
		IQueryable<Partner> Partners
		{
			get;
		}
		IQueryable<OrderDetail> OrderDetails
		{
			get;
		}
		IQueryable<Order> Orders
		{
			get;
		}
		IQueryable<Customer> Customers
		{
			get;
		}
		IQueryable<Billing> Billings
		{
			get;
		}
	}
}
#pragma warning restore 1591
