#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace OBMPDataModel	
{
	public partial class OrderEvent
	{
		private long _iD;
		public virtual long ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private long _orderID;
		public virtual long OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private DateTime? _eventDate;
		public virtual DateTime? EventDate
		{
			get
			{
				return this._eventDate;
			}
			set
			{
				this._eventDate = value;
			}
		}
		
		private string _event;
		public virtual string Event
		{
			get
			{
				return this._event;
			}
			set
			{
				this._event = value;
			}
		}
		
		private long? _userID;
		public virtual long? UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
