#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OBMPDataModel;

namespace OBMPDataModel	
{
	public partial class OrderDetail
	{
		private long? _salesOrderID;
		public virtual long? SalesOrderID
		{
			get
			{
				return this._salesOrderID;
			}
			set
			{
				this._salesOrderID = value;
			}
		}
		
		private long _salesOrderDetailID;
		public virtual long SalesOrderDetailID
		{
			get
			{
				return this._salesOrderDetailID;
			}
			set
			{
				this._salesOrderDetailID = value;
			}
		}
		
		private long? _customerID;
		public virtual long? CustomerID
		{
			get
			{
				return this._customerID;
			}
			set
			{
				this._customerID = value;
			}
		}
		
		private int? _partnerID;
		public virtual int? PartnerID
		{
			get
			{
				return this._partnerID;
			}
			set
			{
				this._partnerID = value;
			}
		}
		
		private long? _productID;
		public virtual long? ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private long? _unitPrice;
		public virtual long? UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
		private long? _unitPriceDiscount;
		public virtual long? UnitPriceDiscount
		{
			get
			{
				return this._unitPriceDiscount;
			}
			set
			{
				this._unitPriceDiscount = value;
			}
		}
		
		private int? _orderQuantity;
		public virtual int? OrderQuantity
		{
			get
			{
				return this._orderQuantity;
			}
			set
			{
				this._orderQuantity = value;
			}
		}
		
		private long? _lineTotal;
		public virtual long? LineTotal
		{
			get
			{
				return this._lineTotal;
			}
			set
			{
				this._lineTotal = value;
			}
		}
		
		private int? _optusStatus;
		public virtual int? OptusStatus
		{
			get
			{
				return this._optusStatus;
			}
			set
			{
				this._optusStatus = value;
			}
		}
		
		private int? _optusUpdatedBy;
		public virtual int? OptusUpdatedBy
		{
			get
			{
				return this._optusUpdatedBy;
			}
			set
			{
				this._optusUpdatedBy = value;
			}
		}
		
		private DateTime? _optusUpdateDate;
		public virtual DateTime? OptusUpdateDate
		{
			get
			{
				return this._optusUpdateDate;
			}
			set
			{
				this._optusUpdateDate = value;
			}
		}
		
		private int? _partnerStatus;
		public virtual int? PartnerStatus
		{
			get
			{
				return this._partnerStatus;
			}
			set
			{
				this._partnerStatus = value;
			}
		}
		
		private int? _partnerUpdatedBy;
		public virtual int? PartnerUpdatedBy
		{
			get
			{
				return this._partnerUpdatedBy;
			}
			set
			{
				this._partnerUpdatedBy = value;
			}
		}
		
		private DateTime? _partnerUpdateDate;
		public virtual DateTime? PartnerUpdateDate
		{
			get
			{
				return this._partnerUpdateDate;
			}
			set
			{
				this._partnerUpdateDate = value;
			}
		}
		
		private int? _customerStatus;
		public virtual int? CustomerStatus
		{
			get
			{
				return this._customerStatus;
			}
			set
			{
				this._customerStatus = value;
			}
		}
		
		private int? _customerUpdatedBy;
		public virtual int? CustomerUpdatedBy
		{
			get
			{
				return this._customerUpdatedBy;
			}
			set
			{
				this._customerUpdatedBy = value;
			}
		}
		
		private DateTime? _customerUpdateDate;
		public virtual DateTime? CustomerUpdateDate
		{
			get
			{
				return this._customerUpdateDate;
			}
			set
			{
				this._customerUpdateDate = value;
			}
		}
		
		private Order _order;
		public virtual Order Order
		{
			get
			{
				return this._order;
			}
			set
			{
				this._order = value;
			}
		}
		
		private Partner _partner;
		public virtual Partner Partner
		{
			get
			{
				return this._partner;
			}
			set
			{
				this._partner = value;
			}
		}
		
		private Product _product;
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
		}
		
	}
}
#pragma warning restore 1591
