#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using OBMPDataModel;

namespace OBMPDataModel	
{
	public partial class Partner
	{
		private int _iD;
		[Required()]
		[Key()]
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _name;
		[StringLength(50)]
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _mSAReference;
		[StringLength(20)]
		public virtual string MSAReference
		{
			get
			{
				return this._mSAReference;
			}
			set
			{
				this._mSAReference = value;
			}
		}
		
		private string _address;
		[StringLength(100)]
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _partnerType;
		[StringLength(20)]
		public virtual string PartnerType
		{
			get
			{
				return this._partnerType;
			}
			set
			{
				this._partnerType = value;
			}
		}
		
		private byte? _partnerShare;
		public virtual byte? PartnerShare
		{
			get
			{
				return this._partnerShare;
			}
			set
			{
				this._partnerShare = value;
			}
		}
		
		private DateTime? _dateRegistered;
		[DataType(DataType.DateTime)]
		public virtual DateTime? DateRegistered
		{
			get
			{
				return this._dateRegistered;
			}
			set
			{
				this._dateRegistered = value;
			}
		}
		
		private string _primaryContact;
		[StringLength(25)]
		public virtual string PrimaryContact
		{
			get
			{
				return this._primaryContact;
			}
			set
			{
				this._primaryContact = value;
			}
		}
		
		private string _primaryContactDetail;
		[StringLength(100)]
		public virtual string PrimaryContactDetail
		{
			get
			{
				return this._primaryContactDetail;
			}
			set
			{
				this._primaryContactDetail = value;
			}
		}
		
		private string _secondaryContact;
		[StringLength(25)]
		public virtual string SecondaryContact
		{
			get
			{
				return this._secondaryContact;
			}
			set
			{
				this._secondaryContact = value;
			}
		}
		
		private string _secondaryContactDetail;
		[StringLength(100)]
		public virtual string SecondaryContactDetail
		{
			get
			{
				return this._secondaryContactDetail;
			}
			set
			{
				this._secondaryContactDetail = value;
			}
		}
		
		private string _technicalContact;
		[StringLength(25)]
		public virtual string TechnicalContact
		{
			get
			{
				return this._technicalContact;
			}
			set
			{
				this._technicalContact = value;
			}
		}
		
		private string _technicalContactDetail;
		[StringLength(100)]
		public virtual string TechnicalContactDetail
		{
			get
			{
				return this._technicalContactDetail;
			}
			set
			{
				this._technicalContactDetail = value;
			}
		}
		
		private string _adminContact;
		[StringLength(25)]
		public virtual string AdminContact
		{
			get
			{
				return this._adminContact;
			}
			set
			{
				this._adminContact = value;
			}
		}
		
		private string _adminContactDetail;
		[StringLength(100)]
		public virtual string AdminContactDetail
		{
			get
			{
				return this._adminContactDetail;
			}
			set
			{
				this._adminContactDetail = value;
			}
		}
		
		private string _escalation;
		[StringLength(100)]
		public virtual string Escalation
		{
			get
			{
				return this._escalation;
			}
			set
			{
				this._escalation = value;
			}
		}
		
		private byte[] _mSAContractDocument;
		public virtual byte[] MSAContractDocument
		{
			get
			{
				return this._mSAContractDocument;
			}
			set
			{
				this._mSAContractDocument = value;
			}
		}
		
		private string _serviceDescription;
		[StringLength(250)]
		public virtual string ServiceDescription
		{
			get
			{
				return this._serviceDescription;
			}
			set
			{
				this._serviceDescription = value;
			}
		}
		
		private IList<Product> _products = new List<Product>();
		public virtual IList<Product> Products
		{
			get
			{
				return this._products;
			}
		}
		
		private IList<Payment> _payments = new List<Payment>();
		public virtual IList<Payment> Payments
		{
			get
			{
				return this._payments;
			}
		}
		
		private IList<OrderDetail> _orderDetails = new List<OrderDetail>();
		public virtual IList<OrderDetail> OrderDetails
		{
			get
			{
				return this._orderDetails;
			}
		}
		
	}
}
#pragma warning restore 1591
