#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OBMPDataModel;

namespace OBMPDataModel	
{
	public partial class Payment
	{
		private long _iD;
		public virtual long ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private long? _salesOrderID;
		public virtual long? SalesOrderID
		{
			get
			{
				return this._salesOrderID;
			}
			set
			{
				this._salesOrderID = value;
			}
		}
		
		private int? _partnerID;
		public virtual int? PartnerID
		{
			get
			{
				return this._partnerID;
			}
			set
			{
				this._partnerID = value;
			}
		}
		
		private DateTime? _paymentDate;
		public virtual DateTime? PaymentDate
		{
			get
			{
				return this._paymentDate;
			}
			set
			{
				this._paymentDate = value;
			}
		}
		
		private long? _paidAmount;
		public virtual long? PaidAmount
		{
			get
			{
				return this._paidAmount;
			}
			set
			{
				this._paidAmount = value;
			}
		}
		
		private string _paymentMethod;
		public virtual string PaymentMethod
		{
			get
			{
				return this._paymentMethod;
			}
			set
			{
				this._paymentMethod = value;
			}
		}
		
		private Order _order;
		public virtual Order Order
		{
			get
			{
				return this._order;
			}
			set
			{
				this._order = value;
			}
		}
		
		private Partner _partner;
		public virtual Partner Partner
		{
			get
			{
				return this._partner;
			}
			set
			{
				this._partner = value;
			}
		}
		
	}
}
#pragma warning restore 1591
