#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace OBMPDataModel	
{
	public partial class ProductTieredUsage
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private long _productID;
		public virtual long ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private int? _lower;
		public virtual int? Lower
		{
			get
			{
				return this._lower;
			}
			set
			{
				this._lower = value;
			}
		}
		
		private int? _upper;
		public virtual int? Upper
		{
			get
			{
				return this._upper;
			}
			set
			{
				this._upper = value;
			}
		}
		
		private long? _charge;
		public virtual long? Charge
		{
			get
			{
				return this._charge;
			}
			set
			{
				this._charge = value;
			}
		}
		
	}
}
#pragma warning restore 1591
