#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using OBMPDataModel;

namespace OBMPDataModel	
{
	public partial class Product
	{
		private long _iD;
		public virtual long ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _productCode;
		public virtual string ProductCode
		{
			get
			{
				return this._productCode;
			}
			set
			{
				this._productCode = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _partnerProductName;
		public virtual string PartnerProductName
		{
			get
			{
				return this._partnerProductName;
			}
			set
			{
				this._partnerProductName = value;
			}
		}
		
		private string _sSOTProductName;
		public virtual string SSOTProductName
		{
			get
			{
				return this._sSOTProductName;
			}
			set
			{
				this._sSOTProductName = value;
			}
		}
		
		private string _sAPProductName;
		public virtual string SAPProductName
		{
			get
			{
				return this._sAPProductName;
			}
			set
			{
				this._sAPProductName = value;
			}
		}
		
		private string _gSMISProductName;
		public virtual string GSMISProductName
		{
			get
			{
				return this._gSMISProductName;
			}
			set
			{
				this._gSMISProductName = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private int? _partnerID;
		public virtual int? PartnerID
		{
			get
			{
				return this._partnerID;
			}
			set
			{
				this._partnerID = value;
			}
		}
		
		private DateTime? _dateRegistered;
		public virtual DateTime? DateRegistered
		{
			get
			{
				return this._dateRegistered;
			}
			set
			{
				this._dateRegistered = value;
			}
		}
		
		private DateTime? _effectiveDate;
		public virtual DateTime? EffectiveDate
		{
			get
			{
				return this._effectiveDate;
			}
			set
			{
				this._effectiveDate = value;
			}
		}
		
		private DateTime? _endDate;
		public virtual DateTime? EndDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
		private int? _marketPlaceSectionID;
		public virtual int? MarketPlaceSectionID
		{
			get
			{
				return this._marketPlaceSectionID;
			}
			set
			{
				this._marketPlaceSectionID = value;
			}
		}
		
		private int? _subCategoryID;
		public virtual int? SubCategoryID
		{
			get
			{
				return this._subCategoryID;
			}
			set
			{
				this._subCategoryID = value;
			}
		}
		
		private string _chargeFrequency;
		public virtual string ChargeFrequency
		{
			get
			{
				return this._chargeFrequency;
			}
			set
			{
				this._chargeFrequency = value;
			}
		}
		
		private string _chargeType;
		public virtual string ChargeType
		{
			get
			{
				return this._chargeType;
			}
			set
			{
				this._chargeType = value;
			}
		}
		
		private long? _charge;
		public virtual long? Charge
		{
			get
			{
				return this._charge;
			}
			set
			{
				this._charge = value;
			}
		}
		
		private bool? _applyGST;
		public virtual bool? ApplyGST
		{
			get
			{
				return this._applyGST;
			}
			set
			{
				this._applyGST = value;
			}
		}
		
		private string _revenuShareType;
		public virtual string RevenuShareType
		{
			get
			{
				return this._revenuShareType;
			}
			set
			{
				this._revenuShareType = value;
			}
		}
		
		private int? _fixedOperatorRevenue;
		public virtual int? FixedOperatorRevenue
		{
			get
			{
				return this._fixedOperatorRevenue;
			}
			set
			{
				this._fixedOperatorRevenue = value;
			}
		}
		
		private int? _fixedPartnerRevenue;
		public virtual int? FixedPartnerRevenue
		{
			get
			{
				return this._fixedPartnerRevenue;
			}
			set
			{
				this._fixedPartnerRevenue = value;
			}
		}
		
		private int? _percentageOperatorRevenue;
		public virtual int? PercentageOperatorRevenue
		{
			get
			{
				return this._percentageOperatorRevenue;
			}
			set
			{
				this._percentageOperatorRevenue = value;
			}
		}
		
		private int? _percentagePartnerRevenue;
		public virtual int? PercentagePartnerRevenue
		{
			get
			{
				return this._percentagePartnerRevenue;
			}
			set
			{
				this._percentagePartnerRevenue = value;
			}
		}
		
		private int? _recurringFixedMonth;
		public virtual int? RecurringFixedMonth
		{
			get
			{
				return this._recurringFixedMonth;
			}
			set
			{
				this._recurringFixedMonth = value;
			}
		}
		
		private string _productStatus;
		public virtual string ProductStatus
		{
			get
			{
				return this._productStatus;
			}
			set
			{
				this._productStatus = value;
			}
		}
		
		private Partner _partner;
		public virtual Partner Partner
		{
			get
			{
				return this._partner;
			}
			set
			{
				this._partner = value;
			}
		}
		
		private IList<OrderDetail> _orderDetails = new List<OrderDetail>();
		public virtual IList<OrderDetail> OrderDetails
		{
			get
			{
				return this._orderDetails;
			}
		}
		
	}
}
#pragma warning restore 1591
