//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PartnerProductName { get; set; }
        public string SSOTProductName { get; set; }
        public string SAPProductName { get; set; }
        public string GSMISProductName { get; set; }
        public Nullable<byte> PartnerShareType { get; set; }
        public string ShareValue1 { get; set; }
        public string ShareValue2 { get; set; }
        public string ShareValue3 { get; set; }
        public string ShareValue4 { get; set; }
        public string ShareValue5 { get; set; }
        public string ShareValue6 { get; set; }
        public string ShareValue7 { get; set; }
        public string ShareValue8 { get; set; }
        public string ShareValue9 { get; set; }
        public string ShareValue10 { get; set; }
        public string Description { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public Nullable<System.DateTime> DateRegistered { get; set; }
    }
}
